apiVersion: apps/v1
kind: Deployment
metadata:
  name: jojeda79-deployment
  labels:
    app: jojeda79app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jojeda79app
  template:
    metadata:
      labels:
        app: jojeda79app
    spec:
      containers:
      - name: jojeda79-container
        image: jojeda79deepthinknyx/intel-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jojeda79app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: jojeda79app 
